// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Models.AppMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRolloverCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ShowDaily")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLifeGoal")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowMonthly")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowWeekly")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowYearly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AppMeta");
                });

            modelBuilder.Entity("TodoApp.Models.RecurringCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "DateStr")
                        .IsUnique();

                    b.ToTable("RecurringCompletions");
                });

            modelBuilder.Entity("TodoApp.Models.TodoTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalScheduledDateStr")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecurrenceMask")
                        .HasColumnType("integer");

                    b.Property<int>("RolloverCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduledDateStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TodoApp.Models.RecurringCompletion", b =>
                {
                    b.HasOne("TodoApp.Models.TodoTask", "Task")
                        .WithMany("RecurringCompletions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TodoApp.Models.TodoTask", b =>
                {
                    b.HasOne("TodoApp.Models.TodoTask", "Parent")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TodoApp.Models.TodoTask", b =>
                {
                    b.Navigation("RecurringCompletions");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
